package com.vikas.authsystem.entity;

public enum AuditAction {
    REGISTER_SUCCESS,
    REGISTER_FAILED,
    EMAIL_VERIFICATION_OTP_SENT,
    EMAIL_VERIFICATION_OTP_RESENT,
    EMAIL_VERIFICATION_SUCCESS,
    EMAIL_VERIFICATION_FAILED,
    EMAIL_VERIFICATION_REQUIRED,
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    LOGOUT,
    LOGOUT_FAILED,
    TOKEN_REFRESH,
    TOKEN_REFRESH_FAILED,
    SESSION_REVOKED,
    OTHER_SESSIONS_REVOKED,
    PASSWORD_CHANGE,
    PASSWORD_CHANGE_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_RESET_OTP_SENT,
    PASSWORD_RESET_FAILED,
    PASSWORD_RESET_SUCCESS
}
